lambda_function_name   = "lambda_cadastro_usuarios"
s3_bucket_name         = "fonte-lambda-cadastro"
lambda_s3_key          = "lambda_cadastro.zip"
lambda_role_name       = "lambda_cad_users_exec_role"
s3_backend_bucket_name = "6soat-tfstate"
aws_region             = "sa-east-1"
